### ISSUE TITLE
Cloudflare R2 - Sync Misconfiguration

### ISSUE THREAD

**Issue by UpperCenter** [gobackup/gobackup#107]
Hi,

I am using Cloudflare R2 for backup sync and I believe there is an error with the S3 API implementation.
Cloudflare documentation specifies the endpoint:
> The API is available via the https://<ACCOUNT_ID>.r2.cloudflarestorage.com endpoint. Find your [account ID in the Cloudflare dashboard](https://developers.cloudflare.com/fundamentals/get-started/basic-tasks/find-account-and-zone-ids/).

But `gobackup perform` gives the following error:
```bash
2022/12/10 15:48:49 [Model: test] failed to upload file, RequestError: send request failed
caused by: Post "https://us-east-1.r2.cloudflarestorage.com/test-backups/2022.12.10.15.48.45.tar.gz.enc?uploads=": remote error: tls: handshake failure
```

I think `us-east-1` should be replaced with the Cloudflare account ID.

Full `yml` config:

```yml
models:
  test:
    compress_with:
      type: tgz
    storages:
      localStorage:
        type: local
        keep: 10
        path: /srv/Test/Backups/Local
      cf:
        type: r2
        keep: 10
        bucket: test-backups
        access_key_id: aaaaaaaaaaabbbbbbbbbbbcccccc
        secret_access_key: aaaaaaaaaaabbbbbbbbbbbcccccc
        max_retries: 5
    databases:
      test:
        database: test-db
        type: mysql
        host: localhost
        port: 3306
        username: root
        password: root
    archive:
      includes:
        - /srv/live/test/public/images
    encrypt_with:
      type: openssl
      password: password1
      salt: true
      base64: true
```

**Comment by ZachCheung** [comment]
@UpperCenter Added `account_id` for R2, please try it.

```yaml
storages:
  r2:
    type: r2
    bucket: gobackup
    account_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    path: backups/demo
    access_key_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    secret_access_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
