### ISSUE TITLE
本地路径备份，可以添加一个配置参数，设置备份文件有效天数，到达过期时间，自动删除备份文件吗？

### ISSUE THREAD

**Issue by YUTIAN0** [gobackup/gobackup#120]

**Comment by huacnlee** [comment]
## Cycling Stored Backups

Each Storage supports the keep setting, which specifies how many backups to keep at this location.

For example:

```yml
models:
  my_app:
    storages:
      local_disk:
        type: local
        keep: 10
        path: /data/backups
```

**`keep` as a Number**

If `keep` have specified and once the `keep` limit has been reached, the older backup files will be removed.

GoBackup will save the backup histories in `~/.gobackup/cycler.json`.
