### ISSUE TITLE
perform error invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Baloneo** [gobackup/gobackup#148]
config
```
models:
  db_backup:
    # At 04:05 on every day.
    schedule:
      every: "1day"
      at: "04:05"
    storages:
      local:
        type: local
        keep: 20
        path: /home/xxxxx/db-backups
    databases:
      mysql:
        type: mysql
        host: xxx.com
        port: 3306
        database: xxxx
        username: root
        password: 12222
      exclude_tables:
        - collect
```

error
```
$ gobackup perform            
2023/04/25 16:48:01 [Config] Load config from default path.
2023/04/25 16:48:01 [Config] Other users are able to access /home/siemens/.gobackup/gobackup.yml with mode -rw-rw-r--
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x82b089]

goroutine 1 [running]:
github.com/spf13/viper.(*Viper).find(0x0, {0x135de03, 0x4}, 0x1)
        /home/runner/go/pkg/mod/github.com/spf13/viper@v1.14.0/viper.go:1231 +0x49
github.com/spf13/viper.(*Viper).Get(0x0, {0x135de03?, 0xc000126de0?})
        /home/runner/go/pkg/mod/github.com/spf13/viper@v1.14.0/viper.go:887 +0x4f
github.com/spf13/viper.(*Viper).GetString(0xc0004271e0?, {0x135de03?, 0xe?})
        /home/runner/go/pkg/mod/github.com/spf13/viper@v1.14.0/viper.go:954 +0x1e
github.com/gobackup/gobackup/config.loadDatabasesConfig(0xc000427378)
        /home/runner/work/gobackup/gobackup/config/config.go:233 +0x11b
github.com/gobackup/gobackup/config.loadModel({_, _})
        /home/runner/work/gobackup/gobackup/config/config.go:199 +0x41e
github.com/gobackup/gobackup/config.Init({0x0, 0x0})
        /home/runner/work/gobackup/gobackup/config/config.go:160 +0xa95
main.initApplication(...)
        /home/runner/work/gobackup/gobackup/main.go:142
main.main.func1(0xc00050cd40)
        /home/runner/work/gobackup/gobackup/main.go:80 +0x36
github.com/urfave/cli/v2.(*Command).Run(0xc000361180, 0xc00050cd40, {0xc000503850, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.23.6/command.go:271 +0xa82
github.com/urfave/cli/v2.(*Command).Run(0xc000361680, 0xc00050cc00, {0xc00003a060, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.23.6/command.go:264 +0xcca
github.com/urfave/cli/v2.(*App).RunContext(0xc000000780, {0x18cd588?, 0xc00003e090}, {0xc00003a060, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.23.6/app.go:333 +0x5b6
github.com/urfave/cli/v2.(*App).Run(...)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.23.6/app.go:310
main.main()
        /home/runner/work/gobackup/gobackup/main.go:138 +0xbb3
```
