### ISSUE TITLE
Backups are not performed regularly

### ISSUE THREAD

**Issue by Baloneo** [gobackup/gobackup#149]
Releases: 2.0.1
yml
```
models:
  db_backup:
    schedule:
      corn: "30 13 * * *"
    compress_with:
      type: tgz
    storages:
      local:
        type: local
        keep: 60
        path: /home/xx/db-backups
    databases:
      my_db:
        type: mysql
        host: xx
        port: 3306
        database: xx
        username: root
        password: xx
        exclude_tables:
          - xx

```

gobackup start

no effect
