### ISSUE TITLE
bug: Cannot upload to Aliyun OSS

### ISSUE THREAD

**Issue by ionling** [gobackup/gobackup#158]
Got error:

> SecondLevelDomainForbidden: Please use virtual hosted style to access.

It seems like this bug was introduced by the commit:
https://github.com/gobackup/gobackup/commit/501905c510cfbfbbd05df328ef520b2379791196
and the PR #66.

IMO, we should set `S3ForcePathStyle` to `false` when using OSS, 
or just add a `pathStyle` configuration option to make it more extensible.

**Comment by huacnlee** [comment]
I have test Aliyun OSS on my VPS, it work will.

<img width="981" alt="image" src="https://github.com/gobackup/gobackup/assets/5518/7c9c22a4-0c4c-44c7-8ffd-85efe3242a1b">


Do you have configed the `endpoint`?

```yml
oss:
  type: oss
  bucket: my-bucket
  region: cn-hangzhou
  access_key_id: $OSS_ACCESS_KEY_ID
  secret_access_key: $OSS_ACCESS_KEY_SECRET
```

**Comment by ionling** [comment]
Here is my config:

```yaml
oss:
  type: oss
  bucket: "{{.OSS.Bucket}}"
  region: cn-hongkong
  path: "{{.OSS.Path}}"
  access_key_id: "{{.OSS.AccessKeyID}}"
  secret_access_key: "{{.OSS.SecretAccessKey}}"
  timeout: 300
  max_retries: 3
```

I have not set the `endpoint` option.

I noticed that your region is `ch-hangzhou`, while mine is `cn-hongkong`.
So, I tried again with a new bucket in cn-hangzhou, but it didn't work.

I also noticed that I had set the `path` option, so I removed that option,
but it still didn't work.

Then, I simply deleted the line `cfg.S3ForcePathStyle = aws.Bool(true)`,
and it started working.

Based on this, you can add a debug breakpoint to check if the line 
`cfg.S3ForcePathStyle = aws.Bool(true)` is encountered in your code.
If it is, then the issue might be related to OSS.

Please note that I am using the latest code from the main branch.
