### ISSUE TITLE
Feature request: backups rotation

### ISSUE THREAD

**Issue by ivakinpavel** [gobackup/gobackup#159]
Since it's possible to run gobackup as a daemon, it would be convenient to have an option to keep the storages clean and rotated. 
Let's say,
```yaml
....
storages:
  s3:
    type: s3
    bucket: my-backups
    region: eu-central-1
    min_backups_to_keep: 7
   ...
....
```
Thanks!
