### ISSUE TITLE
Cloudflare R2 Error - `NotImplemented: Header 'x-amz-storage-class'`

### ISSUE THREAD

**Issue by UpperCenter** [gobackup/gobackup#183]
Hello,

I am using the following `yml` configuration:
```yml
models:
  testing:
    compress_with:
      type: tgz
    storages:
      localStorage:
        type: local
        keep: 10
        path: /srv/test/Backups/Local
      cf:
        type: r2
        account_id: id
        keep: 10
        bucket: test-backups
        access_key_id: id
        secret_access_key: key
        max_retries: 5
    notifiers:
      discord:
        type: discord
        url: https://discord.com/api/webhooks/x
    databases:
      mirrorwood:
        database: testing
        type: mysql
        host: localhost
        port: 3306
        username: root
        password: password
    archive:
      includes:
        - /etc/nginx/conf.d
        - /etc/nginx/nginx.conf
    encrypt_with:
      type: openssl
      password: password
      salt: true
      base64: true
```

I have the below error when performing `gobackup perform`
```sh
Storage errors: [NotImplemented: Header 'x-amz-storage-class' with value '' not implemented status code: 501, request id: , host id: ]
```

This error was not present before, but I updated to the latest version and it seems to have broken.
Thanks
