### ISSUE TITLE
[Feature Request] Support user-defined/script backup model

### ISSUE THREAD

**Issue by bobwng** [gobackup/gobackup#213]
gobackup is great so I want to use gobackup to backup my postgresql as well. After some investigation I found that seems gobackup supports only full-backup for now, and it doesn't support Incremental Backup for postgresql database yet.

So i'm wondering if gobackup could support user-defined/script model. and then users can extend their-own backup script, it might be something like in gobackup.yml:

```yaml
models:
  my_custom_app:
    backup_script:
      path: /path/to/my/backup_script.sh
    split_with:
      chunk_size: 100m
    storages:
      local:
        type: local
        keep: 10
        path: /data/backups
    archive:
      includes:
        - /data/home/git/my-beancount-template
```

It is better keep to support Splitter/Encryptor in such model.
