### ISSUE TITLE
Can I specify a list in the 'database' field?

### ISSUE THREAD

**Issue by fwt11** [gobackup/gobackup#214]
I have created many databases under a database management software. Of course, their host, username, and password are the same. Can I specify a list in the 'database' field?

**Comment by huacnlee** [comment]
NO, by currently design, one database with on model.

**Comment by fwt11** [comment]
Then, is there a way that I don't have to repeatedly specify the host, username, and password?

**Comment by huacnlee** [comment]
You can try using the YAML default function to put the configuration of the same data into default.

For example:

```yml
app_db_default: &app_db_default
  type: mysql
  host: localhost
  port: 3306
  username: root
  password: root

models:
  my_app:
    databases:
      my_app:
        <<: *app_db_default
        database: my_app_db1
      my_app2:
        <<: *app_db_default
        database: my_app_db2
```
