### ISSUE TITLE
Improve Webhook notify to support split success and failure config. 

### ISSUE THREAD

**Issue by huacnlee** [gobackup/gobackup#230]
https://gobackup.github.io/configuration/notifiers/webhook

```yml
some:
  type: webhook
  url: http://localhost:3000/api/backup-notifiy.json
  success:
    url: http://localhost:3000/api/backup-notifiy/success.json
    method: POST
  failure:
    url: http://localhost:3000/api/backup-notifiy/failure.json
    method: POST
```

If the `success` or `failure` present, use it.

Ref #228
