### ISSUE TITLE
密码中不能包含特殊字符$

### ISSUE THREAD

**Issue by sxqsfun** [gobackup/gobackup#258]
运行：gobackup perform
mysql8中密码包含特殊字符$,提示密码验证失败。
同样密码 mysql -uroot -p 能登录进去。
去掉$, 修改密码, 能正常备份。
配置如下：
```
models:
  test:
    compress_with:
      type: tgz
    storages:
      minio:
        type: minio
        bucket: backup
        endpoint: http://www.test.com
        path: test
        access_key_id: HbJj5BfM6I
        access_key_secret: DL6Wzq0IUxwjUft
    databases:
      test:
        type: mysql
        host: localhost
        port: 3306
        database: test
        username: root
        password: "!@5ti8@x@ii7k$!$O3"
```
