### ISSUE TITLE
bypass SSL verification when backing up to S3 minio

### ISSUE THREAD

**Issue by akbarabdullah1989** [gobackup/gobackup#260]
I found an error like this because my S3 minio uses https, how do I fix it..?

2024/08/18 22:00:33 [Model] RequestError: send request failed
caused by: Post "https://192.168.168.10:9000/app-files-db-ojs-fak-agamaislam/home/hasil-gobackup/2024.08.18.21.59.59.tar.gz?uploads=": tls: failed to verify certificate: x509: cannot validate certificate for 192.168.168.10 because it doesn't contain any IP SANs
2024/08/18 22:00:33 [Notifier] Running 0 Notifiers
2024/08/18 22:00:33 [Model app_file_dan_db_ojs-fai] RequestError: send request failed
caused by: Post "https://192.168.168.10:9000/app-files-db-ojs-fak-agamaislam/home/hasil-gobackup/2024.08.18.21.59.59.tar.gz?uploads=": tls: failed to verify certificate: x509: cannot validate certificate for 192.168.168.10 because it doesn't contain any IP SANs

gobackup.yml file configuration that I use :

```
models:
  app-files-db-ojs-fak-agamaislam:
    compress_with:
      type: tgz
    storages:
      s3:
        type: minio
        endpoint: https://192.168.168.10:9000
        bucket: bucket_app_n_db
        region: us-east-1
        path: /home/hasil-gobackup
        access_key_id: 3pDV6rBOkDOTu05zltL645435rewr
        secret_access_key: 7GEsa9Xq2v542zdK43m5j9d2000CS3BUMlyI2Duasdgdfgdf
        timeout: 300
        max_retries: 3     
    databases:
      DB:
        database: dbname
        type: mysql
        host: localhost
        port: 3306
        username: userdb
        password: passdb
    archive:
      includes:
        - /var/www/html
        - /var/www/files
```
