### ISSUE TITLE
Compressor 生成压缩文件临时目录不存在

### ISSUE THREAD

**Issue by nekoimi** [gobackup/gobackup#263]
配置：
```yaml
models:
  test:
    schedule:
      cron: "* * * * *"
    compress_with:
      type: tgz
    storages:
      local:
        type: local
        keep: 10
        path: /backups/
    archives:
      includes:
        - /etc/hosts
```

压缩文件时会出现临时目录不存在的问题：
![c5615baacb9b08684b4fa81dcdf56f2](https://github.com/user-attachments/assets/c7470a67-2adb-4732-a34b-ccaab0a3a8ae)
