### ISSUE TITLE
"before_script" only supports one shell command. 

### ISSUE THREAD

**Issue by douguohai** [gobackup/gobackup#278]
"before_script" only supports one shell command. I wonder if it could support executing multiple separate shell commands within the YAML file. I know that it's possible to write a separate shell file for execution, but writing them directly in the configuration file should be more flexible.

Could it support executing multiple separate shell commands in the YAML file?

like this

```
models:
  my_backup:
    workdir: /data
    before_script: 
      - echo "Before script"
      - task backup
    after_script: echo "After script"
    schedule:
      # At 04:05 on Sunday.
      cron: "5 4 * * sun"
    storages:
      local:
        type: local
        path: /data/dbback

```
