### ISSUE TITLE
mysqldump: Got error: 2026: "TLS/SSL error: self-signed certificate in certificate chain" when trying to connect

### ISSUE THREAD

**Issue by ZP1314ace** [gobackup/gobackup#311]
When i backup my mysql database,i got that "mysqldump: Got error: 2026: "TLS/SSL error: self-signed certificate in certificate chain" when trying to connect",
mysql version is 9.3.0,and my configure is 
```
web:
  host: 0.0.0.0
  username: user
  password: s0sjwl6Klldk0
models:
  sy_server_backup:
    schedule:
      # cron: "5 4 * * sun"
      every: "1day"
      at: "23:00"
    before_script: |
      echo "before script"
    after_script: |
      echo "after script"
    compress_with:
      type: tgz
    split_with:
      chunk_size: 1g
    storages:
      local:
        type: local
        keep: 20
        path: /root/backups
    databases:
      sy_server:
        database: app
        type: mysql
        host: sy.atcaa.win
        port: 3306
        username: root
        password: 123456
        args: --single-transaction --quick
```
